apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ctx
resources:
- configmap.yaml
- cronjob-sync.yaml
images:
- name: ghcr.io/charemma/ctx
  newName: ghcr.io/charemma/ctx
  newTag: latest
